# Pedante pero útil
pedantic = true
# Permisos
allow = [
    "clippy::module_name_repetitions",
    "clippy::must_use_candidate",
    "clippy::cast_precision_loss",
]
# Deny
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::await_holding_lock",
    "clippy::dbg_macro",
    "clippy::print_stdout",
    "clippy::println_empty_string",
]
